
version: '3'

services:
    web:
        build: .
        container_name: Django_csv_googleMaps
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
          - .:/app
        ports:
          - "8000:8000"
        depends_on: 
          - db_postgres
    db_postgres:
        image: postgres
        container_name: postgres_django_csv_googleMaps
        
        environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
            POSTGRES_PASSWORD: postgres
        ports:
          - "5436:5432"            
        volumes:
            - db_data:/var/lib/postgresql/data/

volumes:
    db_data: